Repository hyfi06/platzi-master-end-game, pull requests merged in 2020-05, with the labels that each got.

#2 Add initial environment with NextJS
  .babelrc
  .eslintrc.json
  .gitignore
  README.md
  jest.config.js
  jest.setup.js
  next.config.js
  package-lock.json
  package.json
  public/static/favicon.ico
  src/__mocks__/styleMock.js
  src/__mocks__/svgrMock.js
  src/__test__/Home.test.js
  src/assets/icons/logo.svg
  src/assets/styles/pages/index.scss
  src/components/Title.jsx
  src/pages/_document.jsx
  src/pages/index.jsx
Labels: enhancement

#7 Add global and vars styles
  src/assets/styles/main.scss
  src/assets/styles/pages/index.scss
  src/assets/styles/vars.scss
  src/pages/_document.jsx
Labels: enhancement

#8 Add UI Elements
  src/assets/styles/classes.scss
  src/assets/styles/main.scss
  src/assets/styles/pages/ui.scss
  src/pages/ui.jsx
Labels: documentation

#18 Development design systed created
  src/assets/styles/main.scss
  src/assets/styles/vars.scss
Labels: enhancement

#20 Create login
  package-lock.json
  package.json
  public/favicon.ico
  public/static/favicon.ico
  public/vercel.svg
  src/assets/icons/logo.svg
  src/assets/styles/classes.scss
  src/assets/styles/components/Login.scss
  src/assets/styles/main.scss
  src/assets/styles/mixins.scss
  src/assets/styles/pages/index.scss
  src/assets/styles/vars.scss
  src/components/Login.jsx
  src/pages/_document.jsx
  src/pages/index.js
  src/pages/index.jsx
Labels: enhancement

#22 Created Layout
  .eslintrc
  package.json
  src/assets/icons/logout.svg
  src/assets/icons/user-add.svg
  src/assets/icons/user.svg
  src/assets/icons/users-add.svg
  src/assets/icons/users.svg
  src/assets/styles/components/Header.scss
  src/assets/styles/components/Layout.scss
  src/assets/styles/components/Navbar.scss
  src/assets/styles/main.scss
  src/assets/styles/mixins.scss
  src/assets/styles/pages/index.scss
  src/components/Header.jsx
  src/components/Layout.jsx
  src/components/Navbar.jsx
  src/pages/_app.jsx
  src/pages/index.jsx
Labels: enhancement

#24 Fixed Login and Layout styles
  src/assets/styles/classes.scss
  src/assets/styles/components/Header.scss
  src/assets/styles/components/Layout.scss
  src/assets/styles/components/Login.scss
  src/assets/styles/components/Navbar.scss
  src/assets/styles/mixins.scss
  src/assets/styles/vars.scss
Labels: bug

#31 Added icons
  src/assets/icons/activate.svg
  src/assets/icons/add.svg
  src/assets/icons/close.svg
  src/assets/icons/delete.svg
  src/assets/icons/download.svg
  src/assets/icons/edit.svg
  src/assets/icons/error.svg
  src/assets/icons/file.svg
  src/assets/icons/options.svg
  src/assets/icons/sucess.svg
  src/assets/icons/warning.svg
Labels: enhancement

#32 Created "users" page
  public/default.png
  src/assets/styles/components/Filter.scss
  src/assets/styles/components/Table.scss
  src/assets/styles/mixins.scss
  src/components/Filter.jsx
  src/components/Table.jsx
  src/pages/users.jsx
Labels: enhancement

#33 Add profile page
  src/assets/styles/components/User.scss
  src/assets/styles/components/UserData.scss
  src/assets/styles/pages/addusers.scss
  src/assets/styles/pages/profile.scss
  src/components/User.jsx
  src/components/UserData.jsx
  src/pages/add-users.jsx
  src/pages/profile.jsx
Labels: enhancement

#35 Created Modal layout
  src/assets/styles/components/Modal.scss
  src/assets/styles/vars.scss
  src/components/Modal.jsx
Labels: enhancement

#46 Added Login request
  .eslintrc
  package-lock.json
  package.json
  src/assets/styles/classes.scss
  src/assets/styles/components/Loader.scss
  src/components/Loader.jsx
  src/components/Login.jsx
Labels: enhancement

#48 Added user data in Navbar component
  .eslintrc
  src/assets/styles/components/Navbar.scss
  src/components/Layout.jsx
  src/components/Login.jsx
  src/components/Navbar.jsx
Labels: enhancement

#50 Add session context in Navbar component
  src/assets/styles/classes.scss
  src/assets/styles/components/Filter.scss
  src/components/Filter.jsx
  src/components/Layout.jsx
  src/components/Navbar.jsx
  src/context/SessionContext.jsx
  src/pages/_app.jsx
  src/pages/users.jsx
Labels: enhancement

#52 Data obtained from the api in UsersTable component
  .eslintrc
  src/assets/styles/classes.scss
  src/assets/styles/components/Layout.scss
  src/assets/styles/components/Loader.scss
  src/assets/styles/components/UsersTable.scss
  src/assets/styles/mixins.scss
  src/components/Loader.jsx
  src/components/Login.jsx
  src/components/Navbar.jsx
  src/components/UserRecord.jsx
  src/components/UserRecordOptions.jsx
  src/components/UsersTable.jsx
  src/hooks/useUsers.js
  src/pages/users.jsx
Labels: enhancement

#55 Delete styles unnecesary
  src/assets/styles/components/AddUsersForm.scss
  src/components/AddUsersForm.jsx
Labels: bug

#57 Changed useUser hook to useData
  src/components/UsersTable.jsx
  src/hooks/useData.js
Labels: enhancement

#59 Deleted unnecessary log in UsersTable component
  src/components/UsersTable.jsx
Labels: bug

#60 Add request data in "profile" page
  src/assets/styles/components/Profile.scss
  src/assets/styles/components/User.scss
  src/assets/styles/components/UserData.scss
  src/components/Profile.jsx
  src/components/User.jsx
  src/components/UserData.jsx
  src/pages/profile.jsx
  src/pages/profile/[userID].jsx
Labels: enhancement

#62 61/use request
  src/components/Profile.jsx
  src/components/UsersTable.jsx
  src/hooks/useRequest.js
Labels: enhancement

#64 Created "add-user" page
  public/default.png
  src/assets/icons/success.svg
  src/assets/styles/classes.scss
  src/assets/styles/components/AddUserForm.scss
  src/assets/styles/components/Layout.scss
  src/assets/styles/components/Modal.scss
  src/assets/styles/components/Navbar.scss
  src/assets/styles/mixins.scss
  src/assets/styles/pages/AddUser.scss
  src/components/AddUserForm.jsx
  src/components/Login.jsx
  src/components/Modal.jsx
  src/components/Navbar.jsx
  src/components/UserRecordOptions.jsx
  src/pages/add-user.jsx
  src/pages/profile/[userID].jsx
  src/pages/users.jsx
Labels: enhancement

#67 Added detail page
  .eslintrc
  src/assets/styles/classes.scss
  src/assets/styles/components/Detail.scss
  src/assets/styles/components/User.scss
  src/assets/styles/mixins.scss
  src/components/Detail.jsx
  src/components/Profile.jsx
  src/components/User.jsx
  src/components/UserRecord.jsx
  src/components/UsersTable.jsx
  src/hooks/useRequest.js
  src/pages/detail/[userID].jsx
Labels: enhancement

#69 Created edit-user page
  src/assets/styles/components/EditUserForm.scss
  src/assets/styles/pages/EditUser.scss
  src/components/EditUserForm.jsx
  src/pages/edit-user/[userID].jsx
Labels: enhancement

#72 Added login redirect
  src/components/Login.jsx
Labels: enhancement

#81 Login styles fixed
  src/assets/styles/components/Login.scss
  src/components/Login.jsx
Labels: bug

#86 Users table filter added
  src/assets/styles/classes.scss
  src/assets/styles/components/UsersTable.scss
  src/components/UserRecord.jsx
  src/components/UserRecordOptions.jsx
  src/components/UsersTable.jsx
  src/pages/users.jsx
Labels: enhancement

#89 Login redirect fixed
  src/components/Login.jsx
Labels: bug

#96 UsersTable filter fixed
  src/components/UsersTable.jsx
Labels: bug

#97 Add doctor options
  src/components/Detail.jsx
Labels: enhancement

#99 Add Users page added
  src/assets/styles/classes.scss
  src/assets/styles/components/AddUsersForm.scss
  src/components/AddUsersForm.jsx
  src/pages/add-users.jsx
Labels: enhancement

#103 Logout added
  src/components/Navbar.jsx
Labels: enhancement

#116 112/patient flow
  package-lock.json
  src/assets/styles/components/DetailTest.scss
  src/components/AddResultForm.jsx
  src/components/DetailTest.jsx
  src/components/TemplateForm.jsx
  src/components/TestInfo.jsx
  src/components/TestRecord.jsx
  src/components/TestsTable.jsx
  src/pages/add-result/[orderID].jsx
  src/pages/testDetail/[testID].jsx
Labels: enhancement

#117 Test download page added
  src/assets/styles/classes.scss
  src/assets/styles/components/TestsDownload.scss
  src/assets/styles/mixins.scss
  src/assets/styles/pages/TestDownload.scss
  src/components/TestsDownload.jsx
  src/pages/test-download.jsx
Labels: enhancement

#119 118/test table in detail
  src/assets/styles/components/Detail.scss
  src/components/AddTestForm.jsx
  src/components/Detail.jsx
  src/components/TestInfo.jsx
  src/pages/detail/[userID].jsx
Labels: enhancement

#125 iPad media queries
  src/assets/styles/components/Layout.scss
  src/assets/styles/components/Navbar.scss
  src/assets/styles/mixins.scss
  src/components/Navbar.jsx
Labels: enhancement

#130 Mobile queries
  src/assets/styles/classes.scss
  src/assets/styles/components/AddTestForm.scss
  src/assets/styles/components/AddUserForm.scss
  src/assets/styles/components/AddUsersForm.scss
  src/assets/styles/components/DetailTest.scss
  src/assets/styles/components/EditUserForm.scss
  src/assets/styles/components/Layout.scss
  src/assets/styles/components/Login.scss
  src/assets/styles/components/TemplateForm.scss
  src/assets/styles/components/User.scss
  src/assets/styles/components/UsersTable.scss
  src/assets/styles/mixins.scss
  src/assets/styles/pages/AddTest.scss
  src/assets/styles/pages/AddUser.scss
  src/assets/styles/pages/EditUser.scss
  src/components/AddUserForm.jsx
  src/components/TestsDownload.jsx
Labels: enhancement

#132 [FIX] Layout height fixed
  src/assets/styles/components/Layout.scss
Labels: bug

#134 [FIX] Mobile height disposition fixed
  src/assets/styles/components/Layout.scss
Labels: bug

#138 Logout fixed
  src/components/Login.jsx
  src/components/Navbar.jsx
  src/context/SessionContext.jsx
Labels: bug

#136 Message notification
  src/assets/icons/alarm.svg
  src/assets/styles/classes.scss
  src/components/Layout.jsx
  src/components/TestsTable.jsx
Labels: enhancement

#141 General styles fixed
  src/assets/styles/classes.scss
  src/assets/styles/components/AddTestForm.scss
  src/assets/styles/components/DetailTest.scss
  src/components/AddUserForm.jsx
  src/components/TemplateForm.jsx
  src/components/UserEdit.jsx
  src/pages/dummy.jsx
Labels: bug

#144 Linter styles fixed
  src/components/AddUserForm.jsx
  src/components/Detail.jsx
  src/components/EditUserForm.jsx
  src/components/Login.jsx
Labels: bug
